---
- hosts: all
  vars:
    #swift_version: "swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a"
    swift_version: "swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a"
    examples:  
      - { name: "hello", port: "8080" }
      - { name: "env", port: "8081" }
      - { name: "session", port: "8082" }
      - { name: "my-lib", port: "8083" }
  vars_files:
    - env.yml
  tasks:
    - apt: name={{ item }} state=latest
      with_items:
        - nginx
        - git
        - clang
        - libicu-dev

    - file: path=/etc/nginx/sites-enabled state=absent
    - template: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
    - template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ item.name }}.conf owner=root group=root mode=0644
      with_items: "{{ examples }}"
    - service: name=nginx state=restarted enabled=yes
    - file: path=/var/www/html state=directory owner=root group=root mode=0755
    - template: src=index.j2 dest=/var/www/html/index.html owner=root group=root mode=0644

    - template: src=init.j2 dest=/etc/init/{{ item }}.conf owner=root group=root mode=0644
      with_items:
        - "HelloVapor"
        - "VaporWithEnv"
        - "VaporWithSession"
        - "VaporWithMyLib"

    - copy: src=.profile dest=/root/.profile owner=root group=root mode=0644
    - git: repo=https://github.com/kylef/swiftenv.git dest=/root/.swiftenv
    - command: "/root/.swiftenv/bin/swiftenv install {{ swift_version }}"
      ignore_errors: yes
